version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y nodejs-dev node-gyp libssl1.0-dev
      - apt-get install -y npm
      - apt-get install build-essential checkinstall libssl-dev
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
      - nvm install 8.17.0
      - npm install react-dom
      - npm install react
      - npm install react-router-dom
      - npm install react-router
      - npm install react-scripts
      - npm install react-stripe-elements
      - npm install @material-ui/core
      - npm install @material-ui/icons
      - npm install @material-ui/styles
      - npm install @material-ui/system
      - npm install axios
      - npm install material-design-icons
      - npm install materialize-css
      
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
    - appspec.yml
    ##
  


